[package]
name = "projet_essaim"   
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
noise = "0.8"
bevy = "0.15"
bevy_pancam = "0.17"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "gui"
path = "src/bin/main_bevy.rs"
